[tools]
claude = "latest"
codex = "latest"
gh = "latest"
"github:max-baz/wluma" = "latest"
node = "latest"
"npm:@mem0/cli" = "latest"
"npm:@xai-official/grok" = "latest"
opencode = "latest"
python = "latest"
redis = "8.6.3"
zig = "latest"
zls = "latest"

[settings.upgrade]
auto_prune = false
