monitor.alsa.rules = [
  {
    matches = [
      {
        # Match the output node
        node.name = "alsa_output.usb-Other_World_Computing_Thunderbolt_Go_Dock_Audio_Device-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        # Disable ONLY this node (output)
        node.disabled = true
      }
    }
  }
]
