-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AOC Q27G3XMN 1APRBUA000024",
  mode = "2560x1440@143.91",
  position = "-640x0",
  scale = 1.33333,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1",
  mode = "2880x1920@120.00",
  position = "1280x192",
  scale = 2,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL S2725QS J84BT84",
  mode = "3840x2160@120.00",
  position = "-2560x0",
  scale = 2,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL S2725QS J84BT84", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AOC Q27G3XMN 1APRBUA000024", default = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1", default = true })
