w /sys/bus/pci/devices/0000:00:04.1/power/wakeup - - - - disabled
w /sys/bus/pci/devices/0000:62:00.0/power/wakeup - - - - disabled
w /sys/bus/pci/devices/0000:c3:00.5/power/wakeup - - - - disabled
w /sys/bus/pci/devices/0000:c3:00.3/power/wakeup - - - - disabled
w /sys/bus/pci/devices/0000:c3:00.4/power/wakeup - - - - disabled
w /sys/bus/pci/devices/0000:c3:00.6/power/wakeup - - - - disabled
