[Interface]
Address = 192.168.2.6/32
PrivateKey = {{pass://Main/WireGuard Proton Home/PrivateKey}}
MTU = 1420
PostUp = ip route replace 66.69.36.140/32 via $(ip route show default 0.0.0.0/0 | awk '{print $3; exit}') dev $(ip route show default 0.0.0.0/0 | awk '{print $5; exit}'); ip route replace 192.168.0.0/23 dev %i src 192.168.2.6; ip route replace 192.168.1.157/32 dev %i src 192.168.2.6; resolvectl revert protonwg || true; resolvectl dns %i 192.168.1.157; resolvectl domain %i ~.; resolvectl default-route %i yes
PreDown = resolvectl revert %i; if wg show interfaces 2>/dev/null | tr ' ' '\n' | grep -Fxq protonwg; then resolvectl dns protonwg 10.2.0.1 2a07:b944::2:1; resolvectl domain protonwg ~.; resolvectl default-route protonwg yes; fi

[Peer]
AllowedIPs = 192.168.0.0/23
Endpoint = 66.69.36.140:51820
PublicKey = JlfDamcLh7P4RU6e/NMtgjpQs6A+S0FdC8Y9GJf/Xg8=
PersistentKeepalive = 25
