[Interface]
Address = 10.2.0.2/32, 192.168.2.6/32
PrivateKey = {{pass://Main/WireGuard Proton Home/PrivateKey}}

MTU = 1420
PostUp = ip route replace 192.168.0.0/23 dev %i src 192.168.2.6; ip route replace 192.168.1.157/32 dev %i src 192.168.2.6; resolvectl dns %i 192.168.1.157; resolvectl domain %i ~.; resolvectl default-route %i yes
PreDown = resolvectl revert %i

[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 95.173.221.158:51820
PublicKey = g98KJeIEtR9wbwgVmmaQXR9rEPV+T2RJWf2UE4gB1Ss=

[Peer]
AllowedIPs = 192.168.0.0/23
Endpoint = 66.69.36.140:51820
PublicKey = JlfDamcLh7P4RU6e/NMtgjpQs6A+S0FdC8Y9GJf/Xg8=
