# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,1.5

# My desktop setup
monitor = desc: Dell Inc. DELL S2725QS F889T84, preferred, 0x0, 2
monitor = desc: Dell Inc. DELL S2725QS J84BT84, preferred, auto-left, 2
monitor = desc: BOE NE135A1M-NY1, preferred, auto-right, 2

# Fallback for any other monitor.
monitor=,preferred,auto,1.5

workspace = 1, monitor:desc: Dell Inc. DELL S2725QS J84BT84, default:true
workspace = 2, monitor:desc: Dell Inc. DELL S2725QS F889T84, default:true
workspace = 3, monitor:desc: BOE NE135A1M-NY1, default:true
